Project: Zürich wie neu

1. Introduction

1.1. Research Question

1.2. Relevance

1.3 Datasets

2. Import Libaries and Load Datasets

xxxx

In [48]:
# import libaries
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt #pyplot?
import pyogrio # for checking layers

In [49]:
# paths to datasets
path_neighborhoods = "../data/raw/neighborhoods/statistische_quartiere.gpkg"
path_reports = "../data/raw/zueri-wie-neu-reports/reports.gpkg"
path_population_zh = "../data/raw/population.csv"

In [ ]:
# check what is inside each layer of neighborhoods dataset
for layer_name, _ in pyogrio.list_layers(path_neighborhoods):

    layer_neighborhoods = gpd.read_file(path_neighborhoods, layer=layer_name) 

    print("\n", layer_name) #was ist n
    print(layer_neighborhoods.geom_type.unique())
    print(layer_neighborhoods.head(2))

 stzh.adm_statistische_quartiere_b_p
['Point']
  objid  objectid  ori  hali  vali       name kuerzel  \
0     1         1  0.0   1.0   2.0  Affoltern     111
1     2         2  0.0   1.0   2.0    Seebach     119

                          geometry
0  POINT (2680575.711 1253034.933)
1  POINT (2683071.957 1253148.375)

 stzh.adm_statistische_quartiere_v
['Polygon']
  objid  objectid         qname  qnr    kname  knr  \
0     1         1  Alt-Wiedikon   31  Kreis 3    3
1    10         2       Witikon   74  Kreis 7    7

                                            geometry
0  POLYGON ((2680606.662 1247034.584, 2680626.356...
1  POLYGON ((2685858.632 1246502.629, 2685860.738...

 stzh.adm_statistische_quartiere_map
['Polygon']
   objectid  qnr       qname  knr    kname  \
0         1   73  Hirslanden    7  Kreis 7
1         2   83     Weinegg    8  Kreis 8

                                            geometry
0  POLYGON ((2684457.034 1246514.804, 2684466.315...
1  POLYGON ((2684457.383 1246512.719, 2684458.291...

In [ ]:
# check what is inside each layer of neighborhoods dataset
for layer_name, _ in pyogrio.list_layers(path_neighborhoods):

    layer_neighborhoods = gpd.read_file(path_neighborhoods, layer=layer_name) 

    print("\n", layer_name) #was ist n
    print(layer_neighborhoods.geom_type.unique())
    print(layer_neighborhoods.head(2))

In [53]:
# load the datasets with the relevant layer
neighborhoods = gpd.read_file(path_neighborhoods, layer= "stzh.adm_statistische_quartiere_v") # neighborhoods of Zurich
reports = gpd.read_file(path_reports) # reports from Züri Wie Neu
population_zh = pd.read_csv(path_population_zh) # population of neighborhoods of Zurich (oder pandas nehmen zum einlesen?)

3. Dataset Exploration

xxxx

3.1. Explore the Dataset Neighborhoods
xxx

In [ ]:
# check for shape and correct data types
print(neighborhoods.info())

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   objid     34 non-null     object
 1   objectid  34 non-null     int32
 2   qname     34 non-null     object
 3   qnr       34 non-null     int32
 4   kname     34 non-null     object
 5   knr       34 non-null     int32
 6   geometry  34 non-null     geometry
dtypes: geometry(1), int32(3), object(3)
memory usage: 1.6+ KB
None

In [ ]:
# have a look at what is inside neighborhoods (columns and entries)
display(neighborhoods.head())

,objid,objectid,qname,qnr,kname,knr,geometry
0,1,1,Alt-Wiedikon,31,Kreis 3,3,"POLYGON ((2680606.662 1247034.584, 2680626.356..."
1,10,2,Witikon,74,Kreis 7,7,"POLYGON ((2685858.632 1246502.629, 2685860.738..."
2,11,3,Langstrasse,42,Kreis 4,4,"POLYGON ((2681313.304 1248613.857, 2681459.605..."
3,12,4,Escher Wyss,52,Kreis 5,5,"POLYGON ((2680009.144 1249565.021, 2680055.843..."
4,13,5,Enge,24,Kreis 2,2,"POLYGON ((2681898.171 1246379.668, 2681899.115..."

In [ ]:
# coordinate system used for neighborhoods dataset
print(neighborhoods.crs)

EPSG:2056

3.2. Explore the Dataset Reports
xxx

In [ ]:
# check for shape and correct data types
print(reports.info())

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 73149 entries, 0 to 73148
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   objectid              73149 non-null  int32
 1   service_request_id    73149 non-null  object
 2   requested_datetime    73149 non-null  datetime64[ms]
 3   agency_sent_datetime  72318 non-null  datetime64[ms]
 4   updated_datetime      73149 non-null  datetime64[ms]
 5   e                     73149 non-null  int32
 6   n                     73149 non-null  int32
 7   service_code          73149 non-null  object
 8   service_name          73149 non-null  object
 9   status                73149 non-null  object
 10  userid                73149 non-null  int32
 11  title                 73149 non-null  object
 12  detail                73149 non-null  object
 13  media_url             73149 non-null  object
 14  interface_used        73149 non-null  object
 15  service_notice        73149 non-null  object
 16  description           73149 non-null  object
 17  url                   73149 non-null  object
 18  geometry              73149 non-null  geometry
dtypes: datetime64[ms](3), geometry(1), int32(4), object(11)
memory usage: 9.5+ MB
None

In [ ]:
# have a look at what is inside reports (columns and entries)
display(reports.head())

,objectid,service_request_id,requested_datetime,agency_sent_datetime,updated_datetime,e,n,service_code,service_name,status,userid,title,detail,media_url,interface_used,service_notice,description,url,geometry
0,1,1,2013-03-14 15:16:15,2013-04-04 07:25:05,2013-04-12 07:59:30,2678968,1247548,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Auf dem Asp,Auf dem Asphalt des Bürgersteigs hat es eine E...,,Web interface,Diese Reparatur wird von uns in den kommenden ...,Auf dem Asp: Auf dem Asphalt des Bürgersteigs ...,https://www.zueriwieneu.ch/report/1,POINT (2678968 1247548)
1,2,2,2013-03-14 15:17:57,2013-03-26 14:05:05,2013-04-12 08:00:22,2680746,1249916,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Vermessungs,Vermessungspunkt ist nicht mehr bündig mit dem...,,Web interface,Diese Reparatur wird von uns in den kommenden ...,Vermessungs: Vermessungspunkt ist nicht mehr b...,https://www.zueriwieneu.ch/report/2,POINT (2680746 1249916)
2,3,4,2013-03-15 09:14:16,2013-03-15 09:55:05,2013-04-12 08:08:10,2684605,1251431,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Beim Trotto,Beim Trottoir sind einige Randsteine defekt un...,https://www.zueriwieneu.ch/photo/4.0.jpeg?bfbb...,Web interface,Diese Reparatur wird von uns in den kommenden ...,Beim Trotto: Beim Trottoir sind einige Randste...,https://www.zueriwieneu.ch/report/4,POINT (2684605 1251431)
3,4,5,2013-03-15 09:17:15,2013-03-20 10:05:05,2013-04-12 08:09:05,2681754,1250376,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Auf dem Par,Auf dem Parkplatz beim Waidspital sind einige ...,https://www.zueriwieneu.ch/photo/5.0.jpeg?e309...,Web interface,Diese Reparatur wird von uns in den kommenden ...,Auf dem Par: Auf dem Parkplatz beim Waidspital...,https://www.zueriwieneu.ch/report/5,POINT (2681754 1250376)
4,5,6,2013-03-15 10:36:53,2013-04-22 18:25:05,2013-04-23 13:50:33,2683094,1247762,Abfall/Sammelstelle,Abfall/Sammelstelle,fixed - council,16624,Arbeitskist,Arbeitskiste ist rund herum verschmiert,https://www.zueriwieneu.ch/photo/6.0.jpeg?8e65...,Web interface,Dieses Graffiti wird von uns in den kommenden ...,Arbeitskist: Arbeitskiste ist rund herum versc...,https://www.zueriwieneu.ch/report/6,POINT (2683094 1247762)

In [ ]:
# because there are so many columns, here an overview 
print(reports.columns) # ist in head drin: Löschen aber hat viele Einträge

Index(['objectid', 'service_request_id', 'requested_datetime',
       'agency_sent_datetime', 'updated_datetime', 'e', 'n', 'service_code',
       'service_name', 'status', 'userid', 'title', 'detail', 'media_url',
       'interface_used', 'service_notice', 'description', 'url', 'geometry'],
      dtype='object')

In [ ]:
# coordinate system used for reports dataset
print(reports.crs)

EPSG:2056

3.3. Explore the Dataset Population of Zurich
xxx

In [ ]:
# check for shape and correct data types
print(population_zh.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2785 entries, 0 to 2784
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   StichtagDatJahr  2785 non-null   int64
 1   QuarSort         2785 non-null   int64
 2   QuarLang         2785 non-null   object
 3   AnzBestWir       2785 non-null   int64
dtypes: int64(3), object(1)
memory usage: 87.2+ KB
None

In [66]:
# have a look at what is inside population (columns and entries)
print(population_zh.head())

   StichtagDatJahr  QuarSort QuarLang  AnzBestWir
0             2025        11  Rathaus        3252
1             2024        11  Rathaus        3260
2             2023        11  Rathaus        3343
3             2022        11  Rathaus        3330
4             2021        11  Rathaus        3275

4. Cleaning the Datasets
xxx

4.1. Cleaning Neighborhoods Dataset

In [ ]:
# check for NaNs in neighborhoods
print(neighborhoods.isna().sum())

objid       0
objectid    0
qname       0
qnr         0
kname       0
knr         0
geometry    0
dtype: int64

In [59]:
neighborhoods_clean = neighborhoods[[
    'qname',
    'kname',
    'knr', #evtl auch nicht nötig
    'geometry'
]]

4.2. Cleaning Reports Dataset
only 2014-2025 (full years)
Notiz löschen: only date (year), (e,n, oder geometry), service name (=Kategorie oder service code?), evtl detail oder url, evtl service notice (welche bereits behandelt)

In [64]:
# check for NaNs in reports
print(reports.isna().sum()) # NaNs of agency sent datetime are irrelevant for this analysis

objectid                  0
service_request_id        0
requested_datetime        0
agency_sent_datetime    831
updated_datetime          0
e                         0
n                         0
service_code              0
service_name              0
status                    0
userid                    0
title                     0
detail                    0
media_url                 0
interface_used            0
service_notice            0
description               0
url                       0
geometry                  0
dtype: int64

In [62]:
# filter for reports during full years (2014-2025)
reports_filtered_years = reports[
    (reports['requested_datetime'].dt.year >= 2014) &
    (reports['requested_datetime'].dt.year <= 2025)
]
reports_filtered_years

,objectid,service_request_id,requested_datetime,agency_sent_datetime,updated_datetime,e,n,service_code,service_name,status,userid,title,detail,media_url,interface_used,service_notice,description,url,geometry
188,3540,4001,2014-05-13 07:33:00,2014-05-13 14:10:04,2014-05-13 14:10:04,2682906,1248393,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,external,16624,Hydrant ang,Hydrant angefahren,,iPhone,,Hydrant ang: Hydrant angefahren,https://www.zueriwieneu.ch/report/4001,POINT (2682906 1248393)
709,3134,3554,2014-02-11 01:22:49,2014-02-12 08:55:04,2014-02-12 08:55:04,2684062,1249961,Graffiti,Graffiti,external,16624,Graffiti an,Graffiti an Mauer unterhalb Altherr Terrasse.,,iPhone,,Graffiti an: Graffiti an Mauer unterhalb Althe...,https://www.zueriwieneu.ch/report/3554,POINT (2684062 1249961)
771,4271,4804,2014-08-20 14:49:16,2014-08-20 15:00:05,2014-08-20 15:00:05,2680531,1249514,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,external,16624,S tropft!,S tropft!,https://www.zueriwieneu.ch/photo/4804.0.jpeg?7...,Android,,S tropft!: S tropft!,https://www.zueriwieneu.ch/report/4804,POINT (2680531 1249514)
1023,3152,3577,2014-02-15 19:58:01,2014-02-15 20:00:04,2014-02-17 12:56:33,2681133,1250273,Beleuchtung/Uhren,Beleuchtung/Uhren,fixed - council,16624,Strassenlam,Strassenlampe defekt,,iPhone,Die defekte Lampe wurde ausgewechselt. <br/> F...,Strassenlam: Strassenlampe defekt,https://www.zueriwieneu.ch/report/3577,POINT (2681133 1250273)
1509,7875,8659,2016-06-27 14:31:04,2016-06-27 14:33:03,2016-07-01 07:58:40,2683920,1245604,Brunnen/Hydranten,Brunnen/Hydranten,fixed - council,16624,Brunnen übe,Brunnen überläuft,,iOS,Freundliche Grüsse <br/> <br/> Ihre Stadt Zür...,Brunnen übe: Brunnen überläuft,https://www.zueriwieneu.ch/report/8659,POINT (2683920 1245604)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69261,69248,77265,2025-12-31 15:22:57,2025-12-31 15:27:05,2026-01-05 08:46:40,2681950,1247420,Abfall/Sammelstelle,Abfall/Sammelstelle,fixed - council,2882,Abfall auf,Abfall auf Bank,https://www.zueriwieneu.ch/photo/77265.0.jpeg?...,desktop,Entsorgung + Recycling Zürich reinigt die erwä...,Abfall auf : Abfall auf Bank,https://www.zueriwieneu.ch/report/77265,POINT (2681950 1247420)
69262,69249,77266,2025-12-31 16:13:52,2025-12-31 16:17:05,2026-01-05 08:47:38,2683898,1249678,Abfall/Sammelstelle,Abfall/Sammelstelle,fixed - council,13408,Diese Schmi,Diese Schmiererei ist seit 18.11. leider noch ...,https://www.zueriwieneu.ch/photo/77266.0.jpeg?...,Android,Entsorgung + Recycling Zürich leitet Ihr Anlie...,Diese Schmi: Diese Schmiererei ist seit 18.11....,https://www.zueriwieneu.ch/report/77266,POINT (2683898 1249678)
69263,69250,77267,2025-12-31 16:34:32,2025-12-31 16:37:05,2026-01-05 08:49:29,2681876,1252342,Abfall/Sammelstelle,Abfall/Sammelstelle,fixed - council,18198,Mehrere Aut,Mehrere Autopneus wurden in den Wald geworfen.,,mobile,Entsorgung + Recycling Zürich leitet Ihr Anlie...,Mehrere Aut: Mehrere Autopneus wurden in den W...,https://www.zueriwieneu.ch/report/77267,POINT (2681876 1252342)
69264,69251,77268,2025-12-31 16:55:58,2026-01-06 11:52:05,2026-01-06 11:52:05,2682388,1248654,Allgemein,Allgemein,external,18199,Auf dem Dac,Auf dem Dach der Liegenschaft an der Josefstra...,https://www.zueriwieneu.ch/photo/77268.0.jpeg?...,mobile,Vielen Dank für Ihre Meldung. Wir haben sie an...,Auf dem Dac: Auf dem Dach der Liegenschaft an ...,https://www.zueriwieneu.ch/report/77268,POINT (2682388 1248654)
69265,69252,77269,2025-12-31 23:34:20,2026-01-05 15:12:05,2026-01-06 13:16:14,2683219,1250465,Signalisation/Lichtsignal,Signalisation/Lichtsignal,fixed - council,1141,Diese Abspe,Diese Absperrgitter versperren seit dem Cup Sp...,https://www.zueriwieneu.ch/photo/77269.0.jpeg?...,iOS,Diese Absperrgitter gehören nicht der Stadt Zü...,Diese Abspe: Diese Absperrgitter versperren se...,https://www.zueriwieneu.ch/report/77269,POINT (2683219 1250465)

In [63]:
# selecting important columns only
reports_clean = reports_filtered_years[[
    'requested_datetime',
    'service_name',
    'status',
    'detail',
    'geometry'
]]
reports_clean

,requested_datetime,service_name,status,detail,geometry
188,2014-05-13 07:33:00,Strasse/Trottoir/Platz,external,Hydrant angefahren,POINT (2682906 1248393)
709,2014-02-11 01:22:49,Graffiti,external,Graffiti an Mauer unterhalb Altherr Terrasse.,POINT (2684062 1249961)
771,2014-08-20 14:49:16,Strasse/Trottoir/Platz,external,S tropft!,POINT (2680531 1249514)
1023,2014-02-15 19:58:01,Beleuchtung/Uhren,fixed - council,Strassenlampe defekt,POINT (2681133 1250273)
1509,2016-06-27 14:31:04,Brunnen/Hydranten,fixed - council,Brunnen überläuft,POINT (2683920 1245604)
...,...,...,...,...,...
69261,2025-12-31 15:22:57,Abfall/Sammelstelle,fixed - council,Abfall auf Bank,POINT (2681950 1247420)
69262,2025-12-31 16:13:52,Abfall/Sammelstelle,fixed - council,Diese Schmiererei ist seit 18.11. leider noch ...,POINT (2683898 1249678)
69263,2025-12-31 16:34:32,Abfall/Sammelstelle,fixed - council,Mehrere Autopneus wurden in den Wald geworfen.,POINT (2681876 1252342)
69264,2025-12-31 16:55:58,Allgemein,external,Auf dem Dach der Liegenschaft an der Josefstra...,POINT (2682388 1248654)
69265,2025-12-31 23:34:20,Signalisation/Lichtsignal,fixed - council,Diese Absperrgitter versperren seit dem Cup Sp...,POINT (2683219 1250465)

4.3. Cleaning Population of Zurich Dataset

In [57]:
# check for NaNs in population
print(population_zh.isna().sum())

StichtagDatJahr    0
QuarSort           0
QuarLang           0
AnzBestWir         0
dtype: int64

In [67]:
# select important columns only
popolation_filtered = population_zh[[
    'StichtagDatJahr',
    'QuarLang',
    'AnzBestWir'
]]
popolation_filtered

      StichtagDatJahr    QuarLang  AnzBestWir
0                2025     Rathaus        3252
1                2024     Rathaus        3260
2                2023     Rathaus        3343
3                2022     Rathaus        3330
4                2021     Rathaus        3275
...               ...         ...         ...
2780             1974  Hirzenbach       12759
2781             1973  Hirzenbach       12975
2782             1972  Hirzenbach       13286
2783             1971  Hirzenbach       13627
2784             1970  Hirzenbach       13723

[2785 rows x 3 columns]

In [ ]:
# rename columns in English
population_clean = popolation_filtered.rename(columns={
    'StichtagDatJahr':'year',
    'QuarLang':'qname_pop',
    'AnzBestWir':'population'
})

5. Spatial Join

5.1. Spatial Join Reports Dataset with Neighborhoods Dataset

5.2. Spatial Join Population Dataset with Neighborhoods Dataset